import React from 'react';
import { motion } from 'framer-motion';
import { CheckCircle2, ArrowRight } from 'lucide-react';

const features = [
  {
    title: 'Advanced Business Intelligence',
    desc: 'Access real-time market data, competitor analysis, and predictive models generated by our proprietary AI engine.',
    benefits: ['Real-time market tracking', 'Predictive revenue modeling', 'Automated industry reports'],
    stats: { value: '94%', label: 'Prediction Accuracy' },
    reverse: false,
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80'
  },
  {
    title: 'Venture Capital Facilitation',
    desc: 'Bypass the traditional pitching grind. Our algorithm matches your startup metrics directly with investor mandates for faster term sheets.',
    benefits: ['Algorithmic matchmaking', 'Secure data rooms', 'Automated term sheet generation'],
    stats: { value: 'Rs 25Cr+', label: 'Capital Deployed' },
    reverse: true,
    image: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=800&q=80'
  }
];

export default function FeatureDeepDive() {
  return (
    <section className="py-32 bg-white dark:bg-slate-900-bg overflow-hidden relative">
      <div className="absolute inset-0 bg-noise opacity-30 dark:opacity-50"></div>
      <div className="max-w-7xl mx-auto px-6 lg:px-8 space-y-32 relative z-10">
        {features.map((feat, idx) => (
          <div key={idx} className={`flex flex-col lg:flex-row items-center gap-16 ${feat.reverse ? 'lg:flex-row-reverse' : ''}`}>
            
            {/* Content Side */}
            <motion.div 
              initial={{ opacity: 0, x: feat.reverse ? 50 : -50 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true, margin: "-100px" }}
              transition={{ duration: 0.6 }}
              className="flex-1 space-y-8"
            >
              <div className="space-y-4">
                <h3 className="font-heading font-extrabold text-3xl sm:text-4xl text-slate-900 dark:text-slate-800 leading-tight">
                  {feat.title}
                </h3>
                <p className="text-slate-600 dark:text-[#CBD5E1] text-lg leading-relaxed">
                  {feat.desc}
                </p>
              </div>

              <ul className="space-y-3">
                {feat.benefits.map((b, i) => (
                  <li key={i} className="flex items-center gap-3 text-slate-700 dark:text-slate-600">
                    <CheckCircle2 size={20} className="text-brand-primary-500" />
                    <span className="font-medium">{b}</span>
                  </li>
                ))}
              </ul>

              <div className="pt-6 border-t border-slate-200 dark:border-slate-200 flex items-center justify-between">
                <div>
                  <div className="font-heading font-extrabold text-3xl text-slate-900 dark:text-slate-800">{feat.stats.value}</div>
                  <div className="text-xs text-slate-500 dark:text-slate-600 font-mono uppercase mt-1 tracking-wider font-semibold">{feat.stats.label}</div>
                </div>
                <button className="flex items-center gap-2 text-brand-primary-500 hover:text-brand-primary-400 text-sm font-bold transition-colors group">
                  Explore Module <ArrowRight size={16} className="group-hover:translate-x-1 transition-transform" />
                </button>
              </div>
            </motion.div>

            {/* Image/Mockup Side */}
            <motion.div 
              initial={{ opacity: 0, scale: 0.9, rotateY: feat.reverse ? -10 : 10 }}
              whileInView={{ opacity: 1, scale: 1, rotateY: 0 }}
              viewport={{ once: true, margin: "-100px" }}
              transition={{ duration: 0.8, type: "spring" }}
              className="flex-1 w-full perspective-1000"
            >
              <div className="w-full aspect-[4/3] glass-card rounded-3xl p-2 bg-gradient-to-br from-white/40 to-transparent dark:from-white/5 dark:to-transparent border border-slate-200 dark:border-slate-200 shadow-2xl relative overflow-hidden">
                {/* Simulated UI inside the card */}
                <div className="absolute inset-0 bg-white dark:bg-white m-2 rounded-2xl overflow-hidden border border-slate-200 dark:border-slate-200 flex flex-col shadow-inner">
                  <div className="h-10 bg-slate-50 dark:bg-white/5 border-b border-slate-200 dark:border-slate-200 flex items-center px-4 gap-2">
                     <div className="w-2.5 h-2.5 rounded-full bg-red-400"></div>
                     <div className="w-2.5 h-2.5 rounded-full bg-yellow-400"></div>
                     <div className="w-2.5 h-2.5 rounded-full bg-green-400"></div>
                  </div>
                  <div className="flex-1 relative overflow-hidden bg-white">
                    <img src={feat.image} alt={feat.title} className="absolute inset-0 w-full h-full object-cover opacity-80 mix-blend-screen" />
                    <div className="absolute inset-0 bg-gradient-to-t from-white dark:from-brand-dark-bg via-transparent to-transparent"></div>
                  </div>
                </div>
              </div>
            </motion.div>

          </div>
        ))}
      </div>
    </section>
  );
}
